### ISSUE TITLE
Accord in gulp-stylus installed with npm3

### ISSUE THREAD

**Issue by klausbayrhammer** [jenius/accord#120]
Hi,
I'm raising this issue here as well (see stevelacy/gulp-stylus#148) because I think it's more likely an accord issue than an issue with gulp-stylus itself.

Given to following dependencies we get a different result when we compile our stylus files with all libs installed with npm2 and npm3. In npm3's case it seems like gulp-stylus (which uses accord to load stylus) picks up the wrong stylus version.
```
    "gulp": "^3.9.0",
    "gulp-stylus": "^2.1.0", // gulp-stylus specifies stylus 0.50.x as dependency
    "stylus": "^0.49.3"
```

When installing the project with npm2 the node_modules look like this:

```
node_modules
   |-gulp-stylus
   |---node_modules
   |-----accord
   |-----stylus (0.50.x)
   |-stylus (0.49.x)
```
In this case I expect `require('accord').load('stylus')` located in `gulp-stylus/index.js` to pick up `stylus@0.50.x` since accord and stylus@0.50.x are in the same node_modules directory.

With npm3 the node_modules look like this
```
node_modules
   |-accord
   |-gulp-stylus
   |---node_modules
   |-----stylus (0.50.x)
   |-stylus (0.49.x)
```

 With npm3's dependency layout it looks as if accord picks up stylus@0.49.x because they are both in the root node_modules (although I'd want accord to pick up stylus@0.50.x which is in gulp-stylus' node_modules)

You can use the [klausbayrhammer/gulp-stylus-accord](https://github.com/klausbayrhammer/gulp-stylus-accord) to reproduce the problem.

**Comment by jenius** [comment]
Accord uses basically `require.resolve('stylus')` in order to locate the package (see the code [here](https://github.com/jenius/accord/blob/master/lib/index.coffee#L57)), and as you pointed out node decides how this works. I don't see this as accord's responsibility either, I'm not going to modify `require.resolve`.

Wouldn't an easier fix be to make sure your stylus versions matched, or just rely on a single stylus dependency instead of two? Another option is to use [gulp-accord](https://github.com/carrot/gulp-accord), which is a general accord wrapper that doesn't bundle its own dependencies and relies on the one you installed at the root instead.

Either way I'm going to close this one out as I think accord's behavior in this instance is correct, and even if I'm wrong it's a node-level fix (order or dependency resolution), not in accord's range to fix. But I do appreciate your opening the issue, and doing such a detailed and respectful job of describing the issue! Let me know if there's anything else I can help with :grinning:

**Comment by klausbayrhammer** [comment]
Thanks for your detailed response. We've worked around the issue by making sure the latest stylus dependency is in the root node_modules. Although our setup was a bit trickier than the sample I've provided. We have one stylus dependency in [gulp-stylus](https://github.com/stevelacy/gulp-stylus) (0.50.x) and one in [nib](https://github.com/tj/nib) (0.49.x) and I don't know how npm3 determines which lib should go into to root node_modules. So specifying the latest stylus version as a direct dependency seems to be the only option, or is there another way?

Anyway I have no idea how to solve that problem either (except ugly hacks like specifying a lot of peer-dependencies). Nevertheless somebody else may stumble upon the same issue so it may be a good thing that a workaround is documented in this issue :+1:

**Comment by jenius** [comment]
I'd use [gulp-accord](https://github.com/carrot/gulp-accord) and [axis](https://github.com/jenius/axis) instead. Then you can just stay on the latest stylus version not have any dependency problems :grinning:  Plus axis is actually maintained and is infinitely better than nib.
