### ISSUE TITLE
Slm Support

### ISSUE THREAD

**Issue by mattymaloney** [jenius/accord#147]
Has anyone used *accord* with slm (https://github.com/slm-lang/slm), the javascript port of Slim?

**Comment by jenius** [comment]
Nope! But I would be happy to accept a pull request to add it as a language. Are you interested in contributing one?

**Comment by jenius** [comment]
I'd also question its benefits over jade. Jade has almost exactly the same syntax and is a project with massive support within the js community. It has also been around for a really long time and is very widely used and stable. Unless it has a lot of significant benefits, I don't entirely see a reason why anyone would choose to use it.

**Comment by mattymaloney** [comment]
My primary motivation for using Slm over Jade is for more refined control over whitespace around inline tags. I've gotten the basic render functionality to work as expected, but have hard-coded render options, as I haven't explored getting options from the app.coffee script. I'm sure there's much more missing from my current integration, so it's certainly not worthy of a pull request at this point.

**Comment by jenius** [comment]
If it helps at all, you can use interpolation and the `:` in jade to build code inline and stack selectors on one line respectively. But either way if there's anything I can help with let me know, always happy to check out a PR!

Going to close this issue for now since it's not a problem with accord, but happy to continue discussion here or in the PR thread :grinning:
