### ISSUE TITLE
Using Babel 5 with recent Accord releases?

### ISSUE THREAD

**Issue by davej** [jenius/accord#176]
I upgraded to the latest version of Accord and it seems to break compatibility with Babel 5. Is there a way to get this working or do I need to fork the repo?

**Comment by jenius** [comment]
Unfortunately there isn't, the changes made between babel 5 and 6 we weren't able to smooth over so that they could both work. This is in the release notes: https://github.com/jenius/accord/releases/tag/v0.21.0

If you want to use babel 5, you'll have to use `0.20.0` or less, or upgrade!

**Comment by davej** [comment]
@jenius Would you accept a PR for an override option?

**Comment by jenius** [comment]
what do you mean by an override option?

**Comment by davej** [comment]
I don't know to be honest but I would be up for doing some work to reintroduce Babel 5 support if it's possible?

**Comment by jenius** [comment]
If you could make it happen I'd be happy to check out a PR. I have to warn you it will be immensely difficult though!

**Comment by davej** [comment]
Would it be possible to just have two separate adapters `babel` (for Babel5) and `babel-core` ( for Babel6)?

**Comment by jenius** [comment]
As long as it's not extremely confusing (that naming is), I'm ok with it. `babel` should be the default, which is babel 6. We could add back a "legacy babel" adapter or something maybe?

**Comment by davej** [comment]
Yeah, normally I would just upgrade to the latest version but Babel5 is actually quite useful because it works out of the box without needing any configuration or presets.

I'm wondering though is there a reason why this well be 'immensely difficult' if I just use separate adapters?

**Comment by jenius** [comment]
Separate adapters would make it easier. The original goal was to have accord work with any version of a library, same adapter. But changing the package name we were not prepared for, so we couldn't make it work for this particular babel upgrade internally without vast difficulty.

Adding multiple adapters for a single library is just not ideal, it makes things confusing. Also, I'm pretty sure you would be the only one using the legacy babel adapter, people have generally been able to upgrade to 6 at this point. I mean, babel 6 has been out for more than six months, and this issue was just filed today.

I guess I'm just curious if the effort is worth it. Babel 5 is not supported anymore, and a huge number of significant releases have been pushed to the `v6` line. How long do you plan on continuing to use babel 5? Do you know anyone else who is still using it?

**Comment by davej** [comment]
Babel 5 still has recent releases. It's not cutting-edge but works just fine.

Personally I use Babel 6 for all my projects but Babel 5 is useful for the fact that it's zero-conf and doesn't require additional modules and for that reason I would like to allow support for it in the app I'm working on. The app I'm working on is a bit like a GUI version of Roots.

**Comment by jenius** [comment]
Hey well if you are willing to put in a PR I'll take a look!

**Comment by davej** [comment]
Cool, I've added it to my backlog so I should get around to this in the next couple of weeks.

Related to this, I've added #177 as it may be a nicer way to add adapters without them necessarily needing to be included in the core Accord library.
