### ISSUE TITLE
How do we handle breaking changes in compilers?

### ISSUE THREAD

**Issue by jenius** [jenius/accord#64]
So until this point, I have been assuming that accord's adapters will stay up to date with the latest versions of each compiler, and this was worked fine. However, it is possible that any given compiler could release a major update that breaks things, and requires accord's adapters to change, therefore making them incompatible with older versions. This could cause peoples' code to break who are using accord and have either not upgraded to the latest version of the compiler because they haven't noticed, or haven't had time to do the migration.

This means any update to a compiler which requires accord to change in any way is technically a breaking change. But I don't think we want to say that any time any adapter hosted by accord has a breaking change, accord also has a breaking change, because this will probably result in very fast versioning to a super high number, and also a lot of major version upgrades that most people don't actually care about because they are not using that adapter.

Just a thought here. I don't think this is an emergency, but it definitely is something to think about.

**Comment by FranzSkuffka** [comment]
It seems to me that accord's philosophy is to even out all these differences. I am not completely aware of the possibilities, but shouldn't it be possible to write some code that detects the version/methods of each compiler, caches the results and uses the according adapter-version?

**Comment by stevelacy** [comment]
We had this issue with gulp-less when less@2* came out. 
I would suggest bumping minor versions per peer breakage.

**Comment by slang800** [comment]
We also need to deal with the opposite issue: people using older versions of accord with newer versions of an engine. What we need to do is implement version checking to ensure that the engine is within a particular version range that the adapter supports, and throw a useful error when it isn't. And supporting new versions of compilers should probably be a minor version bump like @stevelacy said, since it won't be changing the interface.

I haven't gotten around to implementing this checking yet, but it's on my list.

**Comment by jenius** [comment]
It would be somewhere between super difficult and impossible for us to smooth out all differences in versions for any library we have an adapter for, so I've gotta say that doesn't seems like the right path.

Minor versions is cool with me, but we'd have to add a big bold note to the top of the readme making note of this because technically this is breaking semver, since any of these minor changes could break your code (regardless of accord's interface).

I think a good first step would be to make accord aware of what version of an engine it is using, then we can take it from there perhaps?

**Comment by slang800** [comment]
Nah, it would still be following semver to use a minor version bump so long as we're not removing support for the old engine versions. And it should be trivial to smooth out the differences - if the interface is basically the same, then we can detect the version and smooth out the differences. Or if the interface is totally different then we can just make a new adapter.

Also, since were only adding support for a new version of the engine, someone who's depending on our accord would need to bump the version of their engine before they get any breaking change... simply bumping the minor version of accord would only add support for the newer engine version, not automatically use it.

**Comment by jenius** [comment]
Sure, if we detect the version and ensure that the old and new ones both work, then it could be minor. But we are nowhere close to having that feature in place at the moment. Also, I'm afraid that supporting every version of every engine that we have an adapter for will make this code really gnarly over time.

Perhaps we should say that whenever we smooth out an interface change such that an older version of an engine still works, we also add a deprecation notice so the user is aware they should upgrade, and eventually phase out support for the older version?

**Comment by slang800** [comment]
I'd actually be ok with gnarliness in this case, so long as it's documented and there for a reason... it's a necessary evil if we want to keep a full range of support for different engines. I suppose we could drop support for the ones that are particularly bad and not very popular (making a major release in the process), but in general we should aim for very high support.

And I think that there is already pressure to get people to upgrade to the latest versions of an engine. Telling the user when to upgrade should be the function of a separate tool since it isn't specific to accord.

**Comment by jenius** [comment]
I don't think the garliness is sustainable in the long term. There have to be some limits in place. I'm ok with having some patches in there temporarily, and reasonable support, but as the maintainer of this library I will not commit to ensuring that every accord adapter works with any version of any of the engines, that's just too much. It will also mean way more tests to cover that kind of stuff, etc. If someone wants continued support for a legacy engine, they can fork accord or lock it to an older version, problem solved.

**Comment by jenius** [comment]
This is currently being handled on the `evergreen` branch. The policy decided upon is that going forward we will support and test all versions of compilers. The structure is changing such that semver ranges are used to define which version of an adapter is compatible with which version(s) of a compiler, and each distinct adapter structure is its own file to avoid gnarliness.

This upgrade will be coming very soon, get pumped!

**Comment by stevelacy** [comment]
w00t :tada:
