### ISSUE TITLE
Less doesn't return an object for sourcemap

### ISSUE THREAD

**Issue by matthew-dean** [jenius/accord#70]
According to the docs:

> Accord returns all source maps as javascript objects

However, for Less I believe the sourcemap is a string, meaning to normalize the adapter, Accord should probably return JSON.parse(sourcemap) for Less.

**Comment by jenius** [comment]
Good catch! Are you sure this is the case though? I have a test in place that confirms it's an object, you can see it here:

https://github.com/jenius/accord/blob/master/test/test.coffee#L777

It's possible that you aren't on the latest version as well, make sure you have checked that too!

**Comment by matthew-dean** [comment]
Welp, I did a npm update, I still get this in Inspector:

![screen shot 2015-01-18 at 5 43 07 pm](https://cloud.githubusercontent.com/assets/414752/5794992/a9d46f8a-9f39-11e4-93d8-b7c5f4acd9bd.png)

Having said that..... this data is being piped from a child process. Could be converting it?

**Comment by jenius** [comment]
Oh yeah you can only pass strings between child processes, you can't pass objects or functions or anything. That's definitely what's doing it.

If you are trying to run compiles in a child process this can make passing some types of locals impossible, but if you're doing it just with less, it might be possible without anything breaking, depending on what less accepts for compiler options. I only mention this because we have tried for quite a long time to figure out how to compile in child processes widely across languages, and don't really have a reliable solution yet that, as many languages accept functions or more complex objects as locals that are destroyed when passed through processes.
