### ISSUE TITLE
Script Language Request - TypeScript

### ISSUE THREAD

**Issue by Anachron** [jenius/accord#8]
Could you add the support for [TypeScript](http://www.typescriptlang.org/)?

**Comment by matthew-dean** [comment]
I don't know if this has changed, but TypeScript has a JavaScript compiler. The library is well-maintained, and now has buy-in from Google / Microsoft, which, not coincidentally, are two major browser makers.

Besides that, if I was going to transition to any JS pre-processing language, TypeScript would be the most obvious choice. So I'd really love to see accord support. Can you take another look?

Incidentally, @Anachron, most parsers worth their salt usually up being extremely verbose in JavaScript. That's because testing for single character codes by number and stringing multiple logical AND or OR tests (and using lots of static functions) is a construct that JIT compilers can optimize the crap out of. Therefore, if you see a parser that looks to be 60000 lines long, it's counter-intuitively probably a lot more performant than a short one that uses regexes and switch statements. Since memory is cheap and it runs server-side, the byte size of the JS doesn't nearly matter as much as how quickly the script executes.

**Comment by slang800** [comment]
@matthew-dean - PR it?

**Comment by matthew-dean** [comment]
![d8b](https://cloud.githubusercontent.com/assets/414752/6586642/3a702bc6-c738-11e4-9bbf-14211501dedd.png)

**Comment by masaeedu** [comment]
@matthew-dean Could you point us to the repo or npm package of the JS implemented compiler? Shouldn't be too hard to wrap and PR.

**Comment by matthew-dean** [comment]
https://github.com/microsoft/typescript

I believe the compilers are in https://github.com/Microsoft/TypeScript/tree/master/bin

To compile, you run tsc from command line, so that's at least the entry point.

**Comment by matthew-dean** [comment]
This may be more useful: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by jenius** [comment]
Haha wow this is brutal. They just won't give you a function that you can pass a string to and it will transform it, or an example in normal js. Either way it does seem to be possible. Would be happy to accept this adapter if someone writes it still!

**Comment by masaeedu** [comment]
@jenius Not sure what you're talking about. That is exactly what the `transpile` method exported by the module does.

Just translated this example from the doc into JS and it seems to work:

    var ts = require("typescript");

    var source = "let x: string  = 'string'";
    var result = ts.transpile(source, { module: ts.ModuleKind.CommonJS });

    console.log(JSON.stringify(result));

Hopefully I'll get around to wrapping this in your API over the weekend.

**Comment by jenius** [comment]
@masaeedu Oh excellent! I must have totally missed that in the linked docs, I'm sorry. Looking forward to checking out the PR, and if you don't think you can handle it let me know and I'll do the wrap as soon as I have time.

**Comment by masaeedu** [comment]
I just took another look, and I just realized it's unfortunately not going to be that easy. It's actually the API in the first snippet we'll need to use. 

It may look excessively convoluted if not used to statically typed languages, but because that module is acting as both a compiler and a linker, it needs to know about *all* the TS files constituting the program. That way it can bork when e.g. someone accidentally mistypes the name of a function exported by some other module.

On the other hand it might be good enough to just transpile every source file as a start.

**Comment by davej** [comment]
Is something like this a possibility? https://github.com/TooTallNate/tsc-single-file/blob/master/bin/tsc-single-file.js

**Comment by jenius** [comment]
Almost, it needs to be a js API rather than a command line API. I'm sure that file could be converted into one though, and that would be awesome :grin:

**Comment by davej** [comment]
Yeah it's just a template for getting started, at least it looks possible to do single file compilation. I'll look into this more over the christmas break.

**Comment by gantony** [comment]
Did anyone evaluate typescript-compiler?
https://www.npmjs.com/package/typescript-compiler

I tried it, seems to work fine. Made a pull request to integrate it into accord: https://github.com/jenius/accord/pull/130

Please let me know what you think.
