### ISSUE TITLE
stylus relative path bug

### ISSUE THREAD

**Issue by contra** [jenius/accord#91]
opening for this person to make sure it doesnt get lost

https://github.com/plus3network/gulp-less/pull/164

they have a fix in this PR but it was outside of accord.

**Comment by jenius** [comment]
I'm not entirely sure I understand the issue in the first place. Spent a minute looking through the commits and the original pull request. It seems like the issue has been fixed already, the reasoning given for the additional changes was that it delegates more to less.

Does 'delegating more to less' actually solve any issues, or prevent any real world bugs? Is there a concrete problem here that's being solved? If there was, and someone could describe to me what it is, I could get a much better handle on what we're trying to accomplish :grinning:

**Comment by contra** [comment]
@jenius I think they are saying its code cleanup by passing an option to less vs. the current impl which is doing it all in accord

**Comment by jenius** [comment]
I think the whole point of accord is to do all options parsing through accord and not less. I may not be understanding this fully though -- I think a concise summary of the issue would really help me a lot here.

**Comment by contra** [comment]
@jenius 

- User saw redundant code, or a better way to structure code
- User pointed out that less already handles this logic via an option
- User sent a PR to pass this option, but it circumvented accord
- I told them to send a PR to accord instead to pass the option

That's the whole story. It isn't any more complex than "lets improve this code since its handled in two places"

I don't have any new info to put forward since I'm just opening this on behalf of the other person, so they can chime in if they want. @jchlapinski

:ok_hand:

**Comment by jenius** [comment]
Hey there @jchaplinski. It seems like you are in no way interested in accord, judging by the discussion in the other issue. In fact, it seems like you are in favor of not using it. If you are interested in continuing this discussion, feel free to chime in here. Otherwise, I'm going to close this issue out.

I'm sure it would be quite simple to get this feature added and pushed out, provided there is a clear description of what exactly it is. The purpose of accord is to simplify options parsing across compiling libraries to make them clear, consistent, and bug free. It will soon also normalize APIs across different versions of compiling libraries automatically. If you would rather build up an API wrapper for less from scratch and maintain it indefinitely, that's fine. The reason that it was switched to accord is that we handle maintaining and thoroughly testing the API wrappers for you, but if you'd rather do it yourself I will take absolutely no offense.

**Comment by jchlapinski** [comment]
Here is my comment regarding gulp-less where I believe there is an actual problem with the way accord is interfacing less: https://github.com/plus3network/gulp-less/pull/164#issuecomment-93025307

@jenius as for the above - with all due respect - accord is introducing bugs on itself, therefore it is not really bug free, and considering current speed at which javascript tools evolve I think it will probably never stay clear, consistent, uniform and bug free for too long. 
Your comment implies that compilers like less are by themselves not bug free, which is probably safe to say, but putting accord on top of them would somehow made them bug free. Now this seem somewhat backwards to me - if you find bugs in LESS or other tool why would you work around it in accord instead of supplying a fix for PR for the original tool? Perhaps I misunderstood. 

As for normalizing API and dealing with breaking changes, well I honestly do not see much point - is it not sufficient to use dependency version for less or whatever in package.json to make sure no breaking changes occur in the given component?

As for writing a wrapper for less "from scratch" - well the wrapper is pretty much written here http://lesscss.org/usage/#programmatic-usage and it should be kept reasonably up-to-date by the very people who made less, would You agree?. And as for maintenance something like this is much easier to maintain and bugfix that api that is dealing with bugs, consistency and breaking changes with many very different tools.

Regards,
Jakub

**Comment by jenius** [comment]
Hey Jakub,

If you have found any bugs, I would love to hear about them! At the moment everything is thoroughly tested and working smoothly. As far as bugs in original compilers, what I mean is not so much mistakes as inconsistencies. Accord's original purpose (still its purpose, to be fair) was for libraries that use many compilers at once. Having to figure out each compiler's interface separately, the way they return objects, sync or async, etc. then coordinate them is a pain. Accord removes that pain.

However, I also would like for it to be useful even for single compiler wrapping libraries by doing the same thing, making everything more consistent. You know how the return object comes back, you know how the source maps come back, and you know exactly how to format the options. On top of that, any additional logic required to configure these things is pushed under the hood so you don't need to deal with it, it's just done, and as a maintainer you have less code in your library to deal with. And finally, we plan to support any version of the library's API, so you don't need to rewrite when they push breaking changes.

Your argument is that, for a single compiler wrapper, there is no advantage to using accord over using the compiler directly. In fact, you are arguing that it's a disadvantage, since adding accord makes another layer in which there could be bugs. This is a reasonable argument, and I understand it. In my opinion, you would be able to create just as good of an abstraction yourself as accord has, or if there's a bug in accord, better, if you plan on building up that wrapper from scratch and maintaining it indefinitely. However, if you want a more hands-off maintenance method, accord is a great option. You know that it will work, be tested and maintained, and grow with the library over time.

This is the reason that Accord uses gulp-less, because it just works and does not need to be maintained or monitored. If you are willing to step up and be a lead maintainer for this library, it seems like @contra is willing to delegate that to you potentially, and once you are in that position if you'd prefer working directly with the less API, that's perfectly acceptable. Whether or not you choose to do this, Accord will continue to maintain a well-tested, functional, and consistent layer on top of less.

**Comment by jenius** [comment]
I'm going to close this issue, since there's no actual issue with Accord here. However still very much open to discussion.

**Comment by jenius** [comment]
So after a bunch of digging I found out what the issue Jakub had been reporting actually was. Just for the record, I'll leave a full report here describing the issue and resolution. The basic issue was that he was unable to manually override the source map basepaths without causing an error.

This error occurred because accord by default attempts to inline all sourcemaps, to guarantee that the maps are read correctly according to the files they were generated from. This decision was made because it's easily possible to screw up mappings if you do not tightly control file locations otherwise, and has been very effective in all implementations of accord's sourcemap functionality so far. Accord uses the `sources` property of the sourcemaps to locate the original files and inline their contents using the `sourcesContent` property, as described in the sourcemaps v2 spec.

When the `sources` property is changed to use relative rather than absolute paths, accord is unable to locate the files' contents from its internals (since they are not relative to accord's internals but rather to another location from which the script was run), and this causes a crash. In the most recent patch, which was deployed in `accord@0.18.0` and is now live on npm, this error is resolved by simply not inlining the sources if they cannot be read correctly, rather than crashing. While I personally am not aware of a situation in which it would be advantageous to use relative sources and not have the `sourcesContent` inlined, this must be a use case for some people, and I hope that this patch makes it easier for them to achieve.

**Comment by jchlapinski** [comment]
@jenius - you are incorrect - "sources" array has nothing to do with including source files content in the sourceContent property or not. Current version of sourcemaps spec you should be looking at is v3 by the way. It is increasingly worrying to me that you fail to understand the problem at hand.
 
It is simply beyond me why would you decide to handle including source contents or otherwise fiddle with sourcemaps already properly generated by a widely used and very well maintained library like less. I personally am not aware of a situation that cannot be handled by the functionality built into less. I am however only addressing using accord to handle less and none other of its apparently numerous use cases, where it indeed might be necessary. This is precisely my point of why this library should not be used for "gulp-less" as continued in https://github.com/plus3network/gulp-less/pull/164

cc @contra

**Comment by jenius** [comment]
As I explained in my previous comment, accord uses the `sources` array in order to populate `sourcesContent` manually, in order to ensure that the correct contents are mapped. The `v2` was a typo, I have corrected it, sorry.

I fully explained in my previous comment exactly why the decision was made to handle sourcemaps in the way that accord currently does. If you read that comment, it will cease to be beyond you, since the decision was explained.

The previous reply here indicated that what I'm saying is not being comprehended, and therefore the discussion is moving nowhere. On top of that, the issue has been discovered, explained, fixed, and closed. Because of this, I'm going to lock this issue now to prevent further spinning of wheels.
